# Form implementation generated from reading ui file 'c:\Users\visti\Desktop\Project\AlgasKalkulators\App\home.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(860, 720)
        Dialog.setStyleSheet("background-color: rgb(84, 84, 84);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 60, 541, 31))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 24pt \"Rockwell\";")
        self.label.setObjectName("label")
        self.Register = QtWidgets.QPushButton(Dialog)
        self.Register.setGeometry(QtCore.QRect(320, 200, 200, 50))
        self.Register.setStyleSheet("font: 14pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.Register.setObjectName("Register")
        self.Quit = QtWidgets.QPushButton(Dialog)
        self.Quit.setGeometry(QtCore.QRect(320, 420, 200, 50))
        self.Quit.setStyleSheet("font: 14pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.Quit.setObjectName("Quit")
        self.Login = QtWidgets.QPushButton(Dialog)
        self.Login.setGeometry(QtCore.QRect(320, 310, 200, 50))
        self.Login.setStyleSheet("font: 14pt \"Rockwell\";\n"
"color: rgb(255, 255, 255);")
        self.Login.setObjectName("Login")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(330, 690, 201, 20))
        self.label_7.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to the Paycheck Calculator"))
        self.Register.setText(_translate("Dialog", "Register"))
        self.Quit.setText(_translate("Dialog", "Quit"))
        self.Login.setText(_translate("Dialog", "Login"))
        self.label_7.setText(_translate("Dialog", "Made by DP3-2 PIKC RVT || 2023"))
