# Form implementation generated from reading ui file 'c:\Users\visti\Desktop\Proejct\AlgasKalkulators\App\hand.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(857, 720)
        Dialog.setStyleSheet("\n"
"background-color: rgb(54, 54, 54);")
        self.Salary = QtWidgets.QLabel(Dialog)
        self.Salary.setGeometry(QtCore.QRect(480, 580, 201, 31))
        self.Salary.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 20pt\n"
" \"Rockwell\";")
        self.Salary.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Salary.setObjectName("Salary")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(210, 580, 201, 31))
        self.label_9.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 20pt\n"
" \"Rockwell\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(350, 690, 201, 20))
        self.label_10.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 40, 495, 539))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 28pt \"Rockwell\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 14pt \"Rockwell\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 18pt \"Rockwell\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.salarySlider = QtWidgets.QSlider(self.layoutWidget)
        self.salarySlider.setMinimum(500)
        self.salarySlider.setMaximum(3000)
        self.salarySlider.setSingleStep(10)
        self.salarySlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.salarySlider.setObjectName("salarySlider")
        self.verticalLayout.addWidget(self.salarySlider)
        self.salary = QtWidgets.QLineEdit(self.layoutWidget)
        self.salary.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Rockwell\";")
        self.salary.setObjectName("salary")
        self.verticalLayout.addWidget(self.salary)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 14pt \"Rockwell\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.depBox = QtWidgets.QComboBox(self.layoutWidget)
        self.depBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Rockwell\";")
        self.depBox.setObjectName("depBox")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.depBox.addItem("")
        self.verticalLayout.addWidget(self.depBox)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 14pt \"Rockwell\";")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.taxBox = QtWidgets.QComboBox(self.layoutWidget)
        self.taxBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Rockwell\";")
        self.taxBox.setObjectName("taxBox")
        self.taxBox.addItem("")
        self.taxBox.addItem("")
        self.verticalLayout.addWidget(self.taxBox)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("color: rgb(255, 246, 230);\n"
"font: 14pt \"Rockwell\";")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.taxRelief = QtWidgets.QLineEdit(self.layoutWidget)
        self.taxRelief.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Rockwell\";")
        self.taxRelief.setFrame(True)
        self.taxRelief.setObjectName("taxRelief")
        self.verticalLayout.addWidget(self.taxRelief)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.calculate = QtWidgets.QPushButton(self.layoutWidget)
        self.calculate.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Rockwell\";")
        self.calculate.setObjectName("calculate")
        self.verticalLayout_2.addWidget(self.calculate)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.home = QtWidgets.QPushButton(self.layoutWidget)
        self.home.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Rockwell\";")
        self.home.setObjectName("home")
        self.verticalLayout_3.addWidget(self.home)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Salary.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "Salary on hand"))
        self.label_10.setText(_translate("Dialog", "Made by DP3-2 PIKC RVT || 2023"))
        self.label.setText(_translate("Dialog", "Paycheck Calculator"))
        self.label_2.setText(_translate("Dialog", "On hand"))
        self.label_3.setText(_translate("Dialog", "Input the salary you get before tax:"))
        self.label_4.setText(_translate("Dialog", "Number of dependents:"))
        self.depBox.setItemText(0, _translate("Dialog", "0"))
        self.depBox.setItemText(1, _translate("Dialog", "1"))
        self.depBox.setItemText(2, _translate("Dialog", "2"))
        self.depBox.setItemText(3, _translate("Dialog", "3"))
        self.depBox.setItemText(4, _translate("Dialog", "4"))
        self.depBox.setItemText(5, _translate("Dialog", "5"))
        self.depBox.setItemText(6, _translate("Dialog", "6"))
        self.depBox.setItemText(7, _translate("Dialog", "7"))
        self.depBox.setItemText(8, _translate("Dialog", "8"))
        self.depBox.setItemText(9, _translate("Dialog", "9"))
        self.label_5.setText(_translate("Dialog", "Salary tax book submitted to the employer:"))
        self.taxBox.setItemText(0, _translate("Dialog", "Yes"))
        self.taxBox.setItemText(1, _translate("Dialog", "No"))
        self.label_6.setText(_translate("Dialog", "Additional tax reliefs:"))
        self.taxRelief.setText(_translate("Dialog", "0"))
        self.calculate.setText(_translate("Dialog", "Calculate"))
        self.home.setText(_translate("Dialog", "Back to Home"))
